// Mock data for FeetBeat dashboard
export const mockHealthData = {
  today: {
    steps: 7842,
    stepsGoal: 10000,
    caloriesBurned: 2150,
    caloriesGoal: 2400,
    activeMinutes: 42,
    activeMinutesGoal: 60,
    distance: 5.2, // km
    floors: 8,
    heartRate: {
      current: 72,
      resting: 62,
      zones: [
        { name: "Fat Burn", min: 104, max: 133, minutes: 18 },
        { name: "Cardio", min: 133, max: 162, minutes: 12 },
        { name: "Peak", min: 162, max: 200, minutes: 5 },
      ],
    },
    hrv: 38,
    hrvAvg7Day: 42,
    sleep: {
      duration: 6.8, // hours
      score: 74,
      stages: {
        deep: 1.2,
        light: 3.4,
        rem: 1.5,
        awake: 0.7,
      },
      startTime: "23:15",
      endTime: "06:03",
    },
    weight: 91.2,
    weightGoal: 85,
    nutrition: {
      calories: 1850,
      caloriesGoal: 2100,
      protein: 92,
      carbs: 210,
      fat: 65,
      sugar: 45,
      fiber: 18,
      water: 1800, // ml
    },
    recoveryScore: 68,
    fatigueScore: 42,
    readinessScore: 72,
  },
  weeklySteps: [
    { day: "Mon", steps: 8200 },
    { day: "Tue", steps: 6500 },
    { day: "Wed", steps: 9100 },
    { day: "Thu", steps: 7200 },
    { day: "Fri", steps: 5800 },
    { day: "Sat", steps: 11200 },
    { day: "Sun", steps: 7842 },
  ],
  weeklySleep: [
    { day: "Mon", hours: 7.2, score: 82 },
    { day: "Tue", hours: 6.5, score: 68 },
    { day: "Wed", hours: 7.8, score: 88 },
    { day: "Thu", hours: 6.1, score: 62 },
    { day: "Fri", hours: 7.0, score: 75 },
    { day: "Sat", hours: 8.2, score: 91 },
    { day: "Sun", hours: 6.8, score: 74 },
  ],
  weeklyWeight: [
    { day: "Mon", weight: 91.8 },
    { day: "Tue", weight: 91.5 },
    { day: "Wed", weight: 91.3 },
    { day: "Thu", weight: 91.6 },
    { day: "Fri", weight: 91.4 },
    { day: "Sat", weight: 91.0 },
    { day: "Sun", weight: 91.2 },
  ],
  weeklyHRV: [
    { day: "Mon", hrv: 44 },
    { day: "Tue", hrv: 40 },
    { day: "Wed", hrv: 46 },
    { day: "Thu", hrv: 38 },
    { day: "Fri", hrv: 41 },
    { day: "Sat", hrv: 45 },
    { day: "Sun", hrv: 38 },
  ],
  recommendations: [
    {
      id: "1",
      type: "activity" as const,
      priority: "high" as const,
      title: "Light 20-minute walk",
      description: "Your recovery score is moderate. A light walk will boost circulation without adding fatigue.",
      icon: "footprints",
    },
    {
      id: "2",
      type: "sleep" as const,
      priority: "high" as const,
      title: "Sleep earlier tonight",
      description: "You have a sleep deficit of 2.4 hours this week. Aim for bed by 22:30.",
      icon: "moon",
    },
    {
      id: "3",
      type: "nutrition" as const,
      priority: "medium" as const,
      title: "Increase protein intake",
      description: "Protein at 92g is below target of 120g. Add a protein-rich snack.",
      icon: "utensils",
    },
    {
      id: "4",
      type: "recovery" as const,
      priority: "medium" as const,
      title: "Avoid intense exercise",
      description: "HRV dropped 12% vs weekly average. Focus on recovery today.",
      icon: "heart-pulse",
    },
    {
      id: "5",
      type: "activity" as const,
      priority: "low" as const,
      title: "Swimming session this weekend",
      description: "Schedule a 30-minute swim to maintain cardio fitness with low joint impact.",
      icon: "waves",
    },
  ],
  meals: [
    {
      id: "1",
      type: "Breakfast" as const,
      time: "07:30",
      items: [
        { name: "Oatmeal with berries", calories: 320, protein: 12, carbs: 52, fat: 8 },
        { name: "Black coffee", calories: 5, protein: 0, carbs: 1, fat: 0 },
      ],
    },
    {
      id: "2",
      type: "Lunch" as const,
      time: "12:30",
      items: [
        { name: "Grilled chicken salad", calories: 450, protein: 38, carbs: 22, fat: 24 },
        { name: "Whole wheat bread", calories: 120, protein: 4, carbs: 22, fat: 2 },
      ],
    },
    {
      id: "3",
      type: "Snack" as const,
      time: "15:30",
      items: [
        { name: "Greek yogurt", calories: 150, protein: 15, carbs: 12, fat: 5 },
        { name: "Almonds (20g)", calories: 120, protein: 4, carbs: 4, fat: 10 },
      ],
    },
    {
      id: "4",
      type: "Dinner" as const,
      time: "19:00",
      items: [
        { name: "Salmon fillet", calories: 380, protein: 35, carbs: 0, fat: 22 },
        { name: "Steamed vegetables", calories: 85, protein: 4, carbs: 16, fat: 1 },
        { name: "Brown rice", calories: 220, protein: 5, carbs: 45, fat: 2 },
      ],
    },
  ],
};
